### ISSUE TITLE
Invalid web link for enhanced-custom-auth-using.html

### ISSUE THREAD

**Issue by vikivivi** [aws/aws-iot-device-sdk-embedded-C#1546]
In the `main` branch, the following web link found in demo source code is no longer valid.
https://docs.aws.amazon.com/iot/latest/developerguide/enhanced-custom-auth-using.html

Is this the correct link?
https://docs.aws.amazon.com/iot/latest/developerguide/custom-auth.html

```sh
grep -rn -B3 "enhanced-custom-auth-using\.html" ./demos/
```
```text
./demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c-596-         * For username and password based authentication in AWS IoT,
./demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c-597-         * #AWS_IOT_PASSWORD_ALPN is used. More details can be found in the
./demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c-598-         * link below.
./demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c:599:         * https://docs.aws.amazon.com/iot/latest/developerguide/enhanced-custom-auth-using.html
--
./demos/ota/ota_demo_core_mqtt/ota_demo_core_mqtt.c-944-         * For username and password based authentication in AWS IoT,
./demos/ota/ota_demo_core_mqtt/ota_demo_core_mqtt.c-945-         * #AWS_IOT_PASSWORD_ALPN is used. More details can be found in the
./demos/ota/ota_demo_core_mqtt/ota_demo_core_mqtt.c-946-         * link below.
./demos/ota/ota_demo_core_mqtt/ota_demo_core_mqtt.c:947:         * https://docs.aws.amazon.com/iot/latest/developerguide/enhanced-custom-auth-using.html
--
./demos/ota/ota_demo_core_http/ota_demo_core_http.c-1070-         * For username and password based authentication in AWS IoT,
./demos/ota/ota_demo_core_http/ota_demo_core_http.c-1071-         * #AWS_IOT_PASSWORD_ALPN is used. More details can be found in the
./demos/ota/ota_demo_core_http/ota_demo_core_http.c-1072-         * link below.
./demos/ota/ota_demo_core_http/ota_demo_core_http.c:1073:         * https://docs.aws.amazon.com/iot/latest/developerguide/enhanced-custom-auth-using.html
```

**Comment by abhidixi11** [comment]
Hello @vikivivi , 
Thanks for pointing it out. 
https://docs.aws.amazon.com/iot/latest/developerguide/custom-auth.html
Looks like the correct link to me. We will update it soon. 
Thanks!

**Comment by vikivivi** [comment]
Hello @abhidixi11 ,
Beside the above link, you might also want to check the following link as well.
https://docs.aws.amazon.com/iot/latest/developerguide/enhanced-custom-authentication.html

```sh
grep -rn "enhanced-custom-authentication" demos/
```

**Comment by leegeth** [comment]
@vikivivi,

Thank you bringing this issue to our attention. We have merged a PR #1552 to address the issues you brought up. Please let us know if you have any further questions or concerns.

**Comment by vikivivi** [comment]
Sorry @leegeth , this link in `demos` is still broken. The other 2 broken links are fixed. Thank you.
https://docs.aws.amazon.com/iot/latest/developerguide/enhanced-custom-auth-using.html
```sh
grep -rn -B3 "enhanced-custom-auth-using\.html" demos/
```

**Comment by vikivivi** [comment]
Thank you @leegeth
